version: '3.9'
services:
  db:
    hostname: mysql
    image: mysql:8
    restart: always
    volumes:
      - db_data:/var/lib/mysqlRaheddin
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3309:3306
  adminer:
    hostname: mysql
    image: adminer
    restart: always
    ports:
      - 8580:8080
volumes:
  db_data:

